version: '2'
services:
  web:
    container_name: fargate-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/web/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    container_name: fargate-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - bundle:/usr/local/bundle
volumes:
  bundle:
    driver: local
