version: '2'
services:
  web:
    container_name: fargate-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - NGINX_HOST=127.0.0.1
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    container_name: fargate-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.deploy
      args:
        - RAILS_ENV=production
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
