version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip3 --version
            pip3 install awscli --upgrade --user
            ~/.local/bin/aws --version
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: |
            docker --version
            docker build --file ./docker/web/Dockerfile --build-arg NGINX_HOST=127.0.0.1 --tag fargate-rails-web .
            docker build --file ./docker/app/Dockerfile --build-arg RAILS_ENV=production --tag fargate-rails-app .
            docker images
#      - run:
#          name: Install Amazon ECS-CLI
#          command: |
#            apk --update-cache --no-cache add curl
#            curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
#            chmod +x /usr/local/bin/ecs-cli
#            ecs-cli --version
#      - run:
#          name: Configure Amazon ECS-CLI profile
#          command: |
#            ecs-cli configure profile --profile-name default --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
#            ecs-cli configure --cluster fargate-rails-cluster --region ap-northeast-1 --default-launch-type FARGATE --config-name fargate-rails
#      - run:
#          name: Compose Service Up
#          command: |
#            ecs-cli compose --cluster-config fargate-rails --file ./docker-compose.deploy.yml service up
workflows:
  build:
    jobs:
      - deploy
