version: 2.1
jobs:
  deploy:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Install Amazon ECS-CLI
          command: |
            apk --update-cache --no-cache add curl
            curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            chmod +x /usr/local/bin/ecs-cli
            ecs-cli --version
      - run:
          name: Configure Amazon ECS-CLI profile
          command: |
            ecs-cli configure profile --profile-name default --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
            ecs-cli configure --cluster fargate-rails-cluster --region ap-northeast-1 --default-launch-type FARGATE --config-name fargate-rails
workflows:
  build:
    jobs:
      - deploy
